### ISSUE TITLE
要不对文件体积5MB以上的字体做个zip压缩？

### ISSUE THREAD

**Issue by ZhianLin** [jaywcjlove/free-font#10]
对字体文件进行zip压缩，减少三分一甚至三分之二的文件体积，龙珠体 Regular、站酷庆科黄油体、令东齐伋体 这三种字体在压缩前后的对比。
![image](https://github.com/user-attachments/assets/2b22b50e-9e3b-40bc-a5b9-38bbda0dace8)
![image](https://github.com/user-attachments/assets/1784d0b1-584b-4ae4-b2bb-c8345cf27f88)
要不对文件体积5MB以上的字体做个zip压缩再存进库里？省空间、省流量、省下载时间，而且zip的普通压缩设置就能达到不错的压缩率了，下载后的解压也没有多么的费时。

**Comment by jaywcjlove** [comment]
![font preview](https://github.com/user-attachments/assets/d1d030a3-91a5-480d-9a11-c221cdf687f8)

@ZhianLin 我曾经想过这个方案，预览页面字体将无法，字体 CDN 也将无法使用，netlify.app 提供免费的 CDN 服务，例如下面字体 CDN 可以直接在 CSS 中使用

```
https://freefont.netlify.app/fonts/胡晓波字体系列/胡晓波骚包体.otf
```

**Comment by jaywcjlove** [comment]
1. 字体将无法在线预览
2. 字体 CDN 没有办法实现

**Comment by hulang** [comment]
@jaywcjlove docs文件夹下的那些：index.html字体列表，怎么不做出：json文件，使用jquery，读取出来，使用模版(比如：`laytpl前端模版引擎`)加载，页面都1万多行了。。做出`json`文件，也容易维护，直接添加到`json`文件里面增加，就自动加载了。。

**Comment by jaywcjlove** [comment]
@hulang 那些页面是脚本自动生成出来的，根据下面 json 生成的静态页面，页面不需要维护

https://github.com/jaywcjlove/free-font/blob/5168d5cc36145227758d94cfcc08ca31367c2fdf/scripts/data.json#L1-L42

如果要维护页面，页面也是 ejs 模板引擎生成的

https://github.com/jaywcjlove/free-font/blob/5168d5cc36145227758d94cfcc08ca31367c2fdf/templates/index.ejs#L1-L10

**Comment by hulang** [comment]
@jaywcjlove 明白了。。。

**Comment by MCBBC** [comment]
可以使用 jszip 来使用浏览器解压zip文件并且转为blob调用

**Comment by jaywcjlove** [comment]
@MCBBC 这样会造成仓库体积变大，因为 git 历史记录，另外还有字体生成预览图片，需要先解压再生成图片....

体积变大会产生费用....
