### ISSUE TITLE
建议增加 postscriptName，字体文件MD5和SHA1，字体文件大小改为字节单位，方便检测字体文件

### ISSUE THREAD

**Issue by guyskk** [jaywcjlove/free-font#8]
需求场景：我从各个地方下载了很多字体，以及我电脑上已经安装了很多字体，我希望判断这些字体是不是免费商用的。
问题：字体名称写法很多，没法和 free-font-data.json 数据对应，需要一种方式找到对应的字体信息。

postscriptName用于唯一标识字体的 PostScript 名称，可以从字体文件中提取出来，放到free-font-data.json 数据里。
https://developer.mozilla.org/zh-CN/docs/Web/API/FontData/postscriptName

字体文件MD5或SHA1可以唯一标识一个文件，但是可能有些字体文件存在版本更新或其他细微差异，导致匹配不上。结合postscriptName 和 MD5/SHA1信息一起判断会最好。

字体文件大小目前是 MB 单位，精确到字节单位方便程序读取，展示的时候转换成MB即可。

**Comment by jaywcjlove** [comment]
@guyskk  已经从字体中读取了一些信息，在界面上展示了部分信息，如版本号 `version`

https://github.com/jaywcjlove/free-font/blob/227bafc725126a610d97d0a25059d4196f0be393/scripts/data.json#L3-L13

**Comment by guyskk** [comment]
这个数据很有用，非常感谢！

**Comment by jaywcjlove** [comment]
@guyskk 字体文件MD5或SHA1，没有读取，这个是要根据文件自动生成的吗？

**Comment by guyskk** [comment]
@jaywcjlove 是的，根据文件内容自动生成

**Comment by jaywcjlove** [comment]
@guyskk 这个暂时没有需要就不生成吧
