### ISSUE TITLE
departure mono pixel font

### ISSUE THREAD

**Issue by bqdong** [jaywcjlove/free-font#9]
https://departuremono.com/

DEPARTURE MONO IS A MONOSPACED PIXEL FONT BY
[HELENA ZHANG](https://helenazhang.com/), LICENSED UNDER [THE SIL OFL](https://openfontlicense.org/).
WEBSITE BUILT BY [TOBIAS FRIED](https://tobiasfried.com/).

**Comment by jaywcjlove** [comment]
@bqdong thx!
